### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by trtpo** [UlyanaKiklevich/PIManager#2]
Ulyana,

I still don't see any correspondence between mockups and requirements. 
Also, please organise your functional requirements into numeric list - one requirement per entry. Hint: if you use "and" in the description of the requirement you can easily make it into more than one requirement!

**Comment by UlyanaKiklevich** [comment]
I see,I'll correct,thank you

**Comment by UlyanaKiklevich** [comment]
Corrected.
